version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
      args:
        BACKEND_PORT: ${BACKEND_PORT}
        FRONTEND_URL: ${FRONTEND_URL}
        FRONTEND_PORT: ${FRONTEND_PORT}
    env_file:
      - .env
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
      args:
        VITE_API_URL: ${BACKEND_URL}
        VITE_API_PORT: ${BACKEND_PORT}
    env_file:
      - .env
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"